# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildandPush
  displayName: Build image and then Push to Dockerhub
  jobs:  
  - job: Build
    displayName: Build
    pool: VMbased
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: 'gabrielmccoll'
        containerRegistry: 'DockerHub'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)